// このファイルは JSON から自動生成されています
// 手動編集しないでください
import type { Poem } from "./poems";

export const hyakuninData: Poem[] = [
  {
    "id": 1,
    "kamiNoKu": "秋の田の かりほの庵の 苫をあらみ",
    "shimoNoKu": "我が衣手は 露にぬれつつ",
    "kamiNoKuKana": "あきのたの かりほのいほの とまをあらみ",
    "shimoNoKuKana": "わがころもでは つゆにぬれつつ",
    "kimariji": "あきの",
    "author": "天智天皇",
    "authorKana": "てんじてんのう",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/0/04/Hyakuninisshu_001.jpg"
  },
  {
    "id": 2,
    "kamiNoKu": "春過ぎて 夏来にけらし 白妙の",
    "shimoNoKu": "衣ほすてふ 天の香具山",
    "kamiNoKuKana": "はるすぎて なつきにけらし しろたへの",
    "shimoNoKuKana": "ころもほすてふ あまのかぐやま",
    "kimariji": "はるす",
    "author": "持統天皇",
    "authorKana": "じとうてんのう",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/9/95/Hyakuninisshu_002.jpg"
  },
  {
    "id": 3,
    "kamiNoKu": "あしびきの 山鳥の尾の しだり尾の",
    "shimoNoKu": "ながながし夜を ひとりかも寝む",
    "kamiNoKuKana": "あしびきの やまどりのをの しだりをの",
    "shimoNoKuKana": "ながながしよを ひとりかもねむ",
    "kimariji": "あし",
    "author": "柿本人麻呂",
    "authorKana": "かきのもとのひとまろ",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/f/f6/Hyakuninisshu_003.jpg"
  },
  {
    "id": 4,
    "kamiNoKu": "田子の浦に うちいでてみれば 白妙の",
    "shimoNoKu": "富士の高嶺に 雪は降りつつ",
    "kamiNoKuKana": "たごのうらに うちいでてみれば しろたへの",
    "shimoNoKuKana": "ふじのたかねに ゆきはふりつつ",
    "kimariji": "たご",
    "author": "山部赤人",
    "authorKana": "やまべのあかひと",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/3/37/Hyakuninisshu_004.jpg"
  },
  {
    "id": 5,
    "kamiNoKu": "奥山に もみぢふみわけ なく鹿の",
    "shimoNoKu": "声聞く時ぞ 秋はかなしき",
    "kamiNoKuKana": "おくやまに もみぢふみわけ なくしかの",
    "shimoNoKuKana": "こゑきくときぞ あきはかなしき",
    "kimariji": "おく",
    "author": "猿丸太夫",
    "authorKana": "さるまるだゆう",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/c/cd/Hyakuninisshu_005.jpg"
  },
  {
    "id": 6,
    "kamiNoKu": "かささぎの 渡せる橋に おく霜の",
    "shimoNoKu": "白きをみれば 夜ぞふけにける",
    "kamiNoKuKana": "かささぎの わたせるはしに おくしもの",
    "shimoNoKuKana": "しろきをみれば よぞふけにける",
    "kimariji": "かさ",
    "author": "中納言家持",
    "authorKana": "ちゅうなごんやかもち",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/f/fe/Hyakuninisshu_006.jpg"
  },
  {
    "id": 7,
    "kamiNoKu": "天の原 ふりさけみれば 春日なる",
    "shimoNoKu": "三笠の山に いでし月かも",
    "kamiNoKuKana": "あまのはら ふりさけみれば かすがなる",
    "shimoNoKuKana": "みかさのやまに いでしつきかも",
    "kimariji": "あまの",
    "author": "阿倍仲麻呂",
    "authorKana": "あべのなかまろ",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/4/46/Hyakuninisshu_007.jpg"
  },
  {
    "id": 8,
    "kamiNoKu": "わが庵は 都のたつみ しかぞすむ",
    "shimoNoKu": "世をうぢ山と 人はいふなり",
    "kamiNoKuKana": "わがいほは みやこのたつみ しかぞすむ",
    "shimoNoKuKana": "よをうぢやまと ひとはいふなり",
    "kimariji": "わがい",
    "author": "喜撰法師",
    "authorKana": "きせんほうし",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/d/d0/Hyakuninisshu_008.jpg"
  },
  {
    "id": 9,
    "kamiNoKu": "花の色は うつりにけりな いたづらに",
    "shimoNoKu": "わが身よにふる ながめせしまに",
    "kamiNoKuKana": "はなのいろは うつりにけりな いたづらに",
    "shimoNoKuKana": "わがみよにふる ながめせしまに",
    "kimariji": "はなの",
    "author": "小野小町",
    "authorKana": "おののこまち",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/9/94/Hyakuninisshu_009.jpg"
  },
  {
    "id": 10,
    "kamiNoKu": "これやこの 行くも帰るも わかれては",
    "shimoNoKu": "しるもしらぬも 逢坂の関",
    "kamiNoKuKana": "これやこの ゆくもかへるも わかれては",
    "shimoNoKuKana": "しるもしらぬも あふさかのせき",
    "kimariji": "これ",
    "author": "蝉丸",
    "authorKana": "せみまる",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/2/29/Hyakuninisshu_010.jpg"
  },
  {
    "id": 11,
    "kamiNoKu": "わたの原 八十島かけて こぎいでぬと",
    "shimoNoKu": "人にはつげよ あまのつり舟",
    "kamiNoKuKana": "わたのはら やそしまかけて こぎいでぬと",
    "shimoNoKuKana": "ひとにはつげよ あまのつりぶね",
    "kimariji": "わたのはら や",
    "author": "参議篁",
    "authorKana": "さんぎたかむら",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/7/7e/Hyakuninisshu_011.jpg"
  },
  {
    "id": 12,
    "kamiNoKu": "天つ風 雲のかよひ路 吹きとぢよ",
    "shimoNoKu": "をとめの姿 しばしとどめむ",
    "kamiNoKuKana": "あまつかぜ くものかよひぢ ふきとぢよ",
    "shimoNoKuKana": "をとめのすがた しばしとどめむ",
    "kimariji": "あまつ",
    "author": "僧正遍昭",
    "authorKana": "そうじょうへんじょう",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/b/b4/Hyakuninisshu_012.jpg"
  },
  {
    "id": 13,
    "kamiNoKu": "つくばねの 峰よりおつる みなの川",
    "shimoNoKu": "恋ぞつもりて 淵となりぬる",
    "kamiNoKuKana": "つくばねの みねよりおつる みなのがは",
    "shimoNoKuKana": "こひぞつもりて ふちとなりぬる",
    "kimariji": "つく",
    "author": "陽成院",
    "authorKana": "ようぜいいん",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/8/85/Hyakuninisshu_013.jpg"
  },
  {
    "id": 14,
    "kamiNoKu": "みちのくの しのぶもぢずり 誰ゆゑに",
    "shimoNoKu": "みだれそめにし 我ならなくに",
    "kamiNoKuKana": "みちのくの しのぶもぢずり たれゆゑに",
    "shimoNoKuKana": "みだれそめにし われならなくに",
    "kimariji": "みち",
    "author": "河原左大臣",
    "authorKana": "かわらのさだいじん",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/9/94/Hyakuninisshu_014.jpg"
  },
  {
    "id": 15,
    "kamiNoKu": "君がため 春の野に出でて 若菜つむ",
    "shimoNoKu": "わが衣手に 雪はふりつつ",
    "kamiNoKuKana": "きみがため はるののにいでて わかなつむ",
    "shimoNoKuKana": "わがころもでに ゆきはふりつつ",
    "kimariji": "きみがため は",
    "author": "光孝天皇",
    "authorKana": "こうこうてんのう",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/0/05/Hyakuninisshu_015.jpg"
  },
  {
    "id": 16,
    "kamiNoKu": "立ちわかれ いなばの山の 峰に生ふる",
    "shimoNoKu": "まつとし聞かば いまかへりこむ",
    "kamiNoKuKana": "たちわかれ いなばのやまの みねにおふる",
    "shimoNoKuKana": "まつとしきかば いまかへりこむ",
    "kimariji": "たち",
    "author": "中納言行平",
    "authorKana": "ちゅうなごんゆきひら",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/8/8b/Hyakuninisshu_016.jpg"
  },
  {
    "id": 17,
    "kamiNoKu": "ちはやぶる 神代もきかず 竜田川",
    "shimoNoKu": "からくれなゐに 水くくるとは",
    "kamiNoKuKana": "ちはやぶる かみよもきかず たつたがは",
    "shimoNoKuKana": "からくれなゐに みづくくるとは",
    "kimariji": "ちは",
    "author": "在原業平朝臣",
    "authorKana": "ありわらのなりひらあそん",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/2/2c/Hyakuninisshu_017.jpg"
  },
  {
    "id": 18,
    "kamiNoKu": "住の江の 岸による波 よるさへや",
    "shimoNoKu": "夢のかよひ路 人目よくらむ",
    "kamiNoKuKana": "すみのえの きしによるなみ よるさへや",
    "shimoNoKuKana": "ゆめのかよひぢ ひとめよくらむ",
    "kimariji": "す",
    "author": "藤原敏行朝臣",
    "authorKana": "ふじわらのとしゆきあそん",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/c/c6/Hyakuninisshu_018.jpg"
  },
  {
    "id": 19,
    "kamiNoKu": "難波潟 みじかき蘆の ふしのまも",
    "shimoNoKu": "あはでこの世を すぐしてよとや",
    "kamiNoKuKana": "なにはがた みじかきあしの ふしのまも",
    "shimoNoKuKana": "あはでこのよを すぐしてよとや",
    "kimariji": "なにはが",
    "author": "伊勢",
    "authorKana": "いせ",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/8/85/Hyakuninisshu_019.jpg"
  },
  {
    "id": 20,
    "kamiNoKu": "わびぬれば いまはたおなじ 難波なる",
    "shimoNoKu": "身をつくしても あはむとぞ思ふ",
    "kamiNoKuKana": "わびぬれば いまはたおなじ なにはなる",
    "shimoNoKuKana": "みをつくしても あはむとぞおもふ",
    "kimariji": "わび",
    "author": "元良親王",
    "authorKana": "もとよししんのう",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/9/97/Hyakuninisshu_020.jpg"
  },
  {
    "id": 21,
    "kamiNoKu": "今こむと いひしばかりに 長月の",
    "shimoNoKu": "有明の月を まちいでつるかな",
    "kamiNoKuKana": "いまこむと いひしばかりに ながつきの",
    "shimoNoKuKana": "ありあけのつきを まちいでつるかな",
    "kimariji": "いまこ",
    "author": "素性法師",
    "authorKana": "そせいほうし",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/3/3b/Hyakuninisshu_021.jpg"
  },
  {
    "id": 22,
    "kamiNoKu": "吹くからに 秋の草木の しをるれば",
    "shimoNoKu": "むべ山風を 嵐といふらむ",
    "kamiNoKuKana": "ふくからに あきのくさきの しをるれば",
    "shimoNoKuKana": "むべやまかぜを あらしといふらむ",
    "kimariji": "ふ",
    "author": "文屋康秀",
    "authorKana": "ふんやのやすひで",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/1/11/Hyakuninisshu_022.jpg"
  },
  {
    "id": 23,
    "kamiNoKu": "月みれば ちぢにものこそ かなしけれ",
    "shimoNoKu": "わが身一つの 秋にはあらねど",
    "kamiNoKuKana": "つきみれば ちぢにものこそ かなしけれ",
    "shimoNoKuKana": "わがみひとつの あきにはあらねど",
    "kimariji": "つき",
    "author": "大江千里",
    "authorKana": "おおえのちさと",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/e/e4/Hyakuninisshu_023.jpg"
  },
  {
    "id": 24,
    "kamiNoKu": "このたびは ぬさもとりあへず 手向山",
    "shimoNoKu": "もみぢのにしき 神のまにまに",
    "kamiNoKuKana": "このたびは ぬさもとりあへず たむけやま",
    "shimoNoKuKana": "もみぢのにしき かみのまにまに",
    "kimariji": "この",
    "author": "菅家",
    "authorKana": "かんけ",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/0/01/Hyakuninisshu_024.jpg"
  },
  {
    "id": 25,
    "kamiNoKu": "名にし負はば 逢坂山の さねかづら",
    "shimoNoKu": "人にしられで 来るよしもがな",
    "kamiNoKuKana": "なにしおはば あふさかやまの さねかづら",
    "shimoNoKuKana": "ひとにしられで くるよしもがな",
    "kimariji": "なにし",
    "author": "三条右大臣",
    "authorKana": "さんじょうのうだいじん",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/d/d2/Hyakuninisshu_025.jpg"
  },
  {
    "id": 26,
    "kamiNoKu": "小倉山 峰のもみぢ葉 心あらば",
    "shimoNoKu": "いまひとたびの みゆきまたなむ",
    "kamiNoKuKana": "をぐらやま みねのもみぢば こころあらば",
    "shimoNoKuKana": "いまひとたびの みゆきまたなむ",
    "kimariji": "をぐ",
    "author": "貞信公",
    "authorKana": "ていしんこう",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/b/b4/Hyakuninisshu_026.jpg"
  },
  {
    "id": 27,
    "kamiNoKu": "みかの原 わきて流るる いづみ川",
    "shimoNoKu": "いつみきとてか 恋しかるらむ",
    "kamiNoKuKana": "みかのはら わきてながるる いづみがは",
    "shimoNoKuKana": "いつみきとてか こひしかるらむ",
    "kimariji": "みかの",
    "author": "中納言兼輔",
    "authorKana": "ちゅうなごんかねすけ",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/7/7b/Hyakuninisshu_027.jpg"
  },
  {
    "id": 28,
    "kamiNoKu": "山里は 冬ぞさびしさ まさりける",
    "shimoNoKu": "人目も草も かれぬと思へば",
    "kamiNoKuKana": "やまざとは ふゆぞさびしさ まさりける",
    "shimoNoKuKana": "ひとめもくさも かれぬとおもへば",
    "kimariji": "やまざ",
    "author": "源宗行朝臣",
    "authorKana": "みなもとのむねゆきあそん",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/a/af/Hyakuninisshu_028.jpg"
  },
  {
    "id": 29,
    "kamiNoKu": "心当てに 折らばや折らむ 初霜の",
    "shimoNoKu": "おきまどはせる 白菊の花",
    "kamiNoKuKana": "こころあてに をらばやをらむ はつしもの",
    "shimoNoKuKana": "おきまどはせる しらぎくのはな",
    "kimariji": "こころあ",
    "author": "凡河内躬恒",
    "authorKana": "おおしこうちのみつね",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/c/cf/Hyakuninisshu_029.jpg"
  },
  {
    "id": 30,
    "kamiNoKu": "有明の つれなく見えし 別れより",
    "shimoNoKu": "あかつきばかり うきものはなし",
    "kamiNoKuKana": "ありあけの つれなくみえし わかれより",
    "shimoNoKuKana": "あかつきばかり うきものはなし",
    "kimariji": "ありあ",
    "author": "壬生忠岑",
    "authorKana": "みぶのただみね",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/8/8a/Hyakuninisshu_030.jpg"
  },
  {
    "id": 31,
    "kamiNoKu": "朝ぼらけ 有明の月と見るまでに 吉野の里に",
    "shimoNoKu": "降れる白雪",
    "kamiNoKuKana": "あさぼらけ ありあけのつきと みるまでに",
    "shimoNoKuKana": "よしののさとに ふれるしらゆき",
    "kimariji": "あさぼらけ あ",
    "author": "坂上是則",
    "authorKana": "さかのうえのこれのり",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/c/ce/Hyakuninisshu_031.jpg"
  },
  {
    "id": 32,
    "kamiNoKu": "山川に 風のかけたる しがらみは",
    "shimoNoKu": "ながれもあへぬ もみぢなりけり",
    "kamiNoKuKana": "やまがはに かぜのかけたる しがらみは",
    "shimoNoKuKana": "ながれもあへぬ もみぢなりけり",
    "kimariji": "やまが",
    "author": "春道列樹",
    "authorKana": "はるみちのつらき",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/a/a6/Hyakuninisshu_032.jpg"
  },
  {
    "id": 33,
    "kamiNoKu": "久方の 光のどけき 春の日に",
    "shimoNoKu": "しづ心なく 花の散るらむ",
    "kamiNoKuKana": "ひさかたの ひかりのどけき はるのひに",
    "shimoNoKuKana": "しづこころなく はなのちるらむ",
    "kimariji": "ひさ",
    "author": "紀友則",
    "authorKana": "きのとものり",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/e/ef/Hyakuninisshu_033.jpg"
  },
  {
    "id": 34,
    "kamiNoKu": "誰をかも しる人にせむ 高砂の",
    "shimoNoKu": "松も昔の 友ならなくに",
    "kamiNoKuKana": "たれをかも しるひとにせむ たかさごの",
    "shimoNoKuKana": "まつもむかしの ともならなくに",
    "kimariji": "たれ",
    "author": "藤原興風",
    "authorKana": "ふじわらのおきかぜ",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/f/f6/Hyakuninisshu_034.jpg"
  },
  {
    "id": 35,
    "kamiNoKu": "人はいさ 心も知らず ふるさとは",
    "shimoNoKu": "花ぞ昔の 香に匂ひける",
    "kamiNoKuKana": "ひとはいさ こころもしらず ふるさとは",
    "shimoNoKuKana": "はなぞむかしの かににほひける",
    "kimariji": "ひとは",
    "author": "紀貫之",
    "authorKana": "きのつらゆき",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/3/32/Hyakuninisshu_035.jpg"
  },
  {
    "id": 36,
    "kamiNoKu": "夏の夜は まだ宵ながら あけぬるを",
    "shimoNoKu": "雲のいづこに 月やどるらむ",
    "kamiNoKuKana": "なつのよは まだよひながら あけぬるを",
    "shimoNoKuKana": "くものいづこに つきやどるらむ",
    "kimariji": "なつ",
    "author": "清原深養父",
    "authorKana": "きよはらのふかやぶ",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/f/f7/Hyakuninisshu_036.jpg"
  },
  {
    "id": 37,
    "kamiNoKu": "白露に 風の吹きしく 秋の野は",
    "shimoNoKu": "つらぬきとめぬ 玉ぞ散りける",
    "kamiNoKuKana": "しらつゆに かぜのふきしく あきののは",
    "shimoNoKuKana": "つらぬきとめぬ たまぞちりける",
    "kimariji": "しら",
    "author": "文屋朝康",
    "authorKana": "ふんやのあさやす",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/c/c5/Hyakuninisshu_037.jpg"
  },
  {
    "id": 38,
    "kamiNoKu": "忘らるる 身をば思はず ちかひてし",
    "shimoNoKu": "人の命の 惜しくもあるかな",
    "kamiNoKuKana": "わすらるる みをばおもはず ちかひてし",
    "shimoNoKuKana": "ひとのいのちの をしくもあるかな",
    "kimariji": "わすら",
    "author": "右近",
    "authorKana": "うこん",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/a/a5/Hyakuninisshu_038.jpg"
  },
  {
    "id": 39,
    "kamiNoKu": "浅茅生の 小野の篠原 しのぶれど",
    "shimoNoKu": "あまりてなどか 人の恋しき",
    "kamiNoKuKana": "あさぢふの をののしのはら しのぶれど",
    "shimoNoKuKana": "あまりてなどか ひとのこひしき",
    "kimariji": "あさぢ",
    "author": "参議等",
    "authorKana": "さんぎひとし",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/7/7b/Hyakuninisshu_039.jpg"
  },
  {
    "id": 40,
    "kamiNoKu": "しのぶれど 色に出でにけり 我が恋は",
    "shimoNoKu": "物や思ふと 人の問ふまで",
    "kamiNoKuKana": "しのぶれど いろにいでにけり わがこひは",
    "shimoNoKuKana": "ものやおもふと ひとのとふまで",
    "kimariji": "しの",
    "author": "平兼盛",
    "authorKana": "たいらのかねもり",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/7/7b/Hyakuninisshu_040.jpg"
  },
  {
    "id": 41,
    "kamiNoKu": "恋すてふ 我が名はまだき 立ちにけり",
    "shimoNoKu": "人しれずこそ 思ひそめしか",
    "kamiNoKuKana": "こひすてふ わがなはまだき たちにけり",
    "shimoNoKuKana": "ひとしれずこそ おもひそめしか",
    "kimariji": "こひ",
    "author": "壬生忠見",
    "authorKana": "みぶのただみ",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/6/61/Hyakuninisshu_041.jpg"
  },
  {
    "id": 42,
    "kamiNoKu": "ちぎりきな かたみに袖を しぼりつつ",
    "shimoNoKu": "末の松山 波こさじとは",
    "kamiNoKuKana": "ちぎりきな かたみにそでを しぼりつつ",
    "shimoNoKuKana": "すゑのまつやま なみこさじとは",
    "kimariji": "ちぎりき",
    "author": "清原元輔",
    "authorKana": "きよはらのもとすけ",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/5/54/Hyakuninisshu_042.jpg"
  },
  {
    "id": 43,
    "kamiNoKu": "あひみての のちの心に くらぶれば",
    "shimoNoKu": "昔は物を 思はざりけり",
    "kamiNoKuKana": "あひみての のちのこころに くらぶれば",
    "shimoNoKuKana": "むかしはものを おもはざりけり",
    "kimariji": "あひ",
    "author": "権中納言敦忠",
    "authorKana": "ごんちゅうなごんあつただ",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/2/2a/Hyakuninisshu_043.jpg"
  },
  {
    "id": 44,
    "kamiNoKu": "あふことの たえてしなくば なかなかに",
    "shimoNoKu": "人をも身をも 恨みざらまし",
    "kamiNoKuKana": "あふことの たえてしなくば なかなかに",
    "shimoNoKuKana": "ひとをもみをも うらみざらまし",
    "kimariji": "あふこ",
    "author": "中納言朝忠",
    "authorKana": "ちゅうなごんあさただ",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/2/2c/Hyakuninisshu_044.jpg"
  },
  {
    "id": 45,
    "kamiNoKu": "あはれとも いふべき人は 思ほえで",
    "shimoNoKu": "身のいたづらに なりぬべきかな",
    "kamiNoKuKana": "あはれとも いふべきひとは おもほえで",
    "shimoNoKuKana": "みのいたづらに なりぬべきかな",
    "kimariji": "あはれ",
    "author": "謙徳公",
    "authorKana": "けんとくこう",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/4/40/Hyakuninisshu_045.jpg"
  },
  {
    "id": 46,
    "kamiNoKu": "由良のとを 渡る舟人 かぢをたえ",
    "shimoNoKu": "ゆくへも知らぬ 恋の道かな",
    "kamiNoKuKana": "ゆらのとを わたるふなびと かぢをたえ",
    "shimoNoKuKana": "ゆくへもしらぬ こひのみちかな",
    "kimariji": "ゆら",
    "author": "曽禰好忠",
    "authorKana": "そねのよしただ",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/5/5a/Hyakuninisshu_046.jpg"
  },
  {
    "id": 47,
    "kamiNoKu": "八重むぐら しげれる宿の さびしきに",
    "shimoNoKu": "人こそ見えね 秋は来にけり",
    "kamiNoKuKana": "やへむぐら しげれるやどの さびしきに",
    "shimoNoKuKana": "ひとこそみえね あきはきにけり",
    "kimariji": "やへ",
    "author": "恵慶法師",
    "authorKana": "えぎょうほうし",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/0/0f/Hyakuninisshu_047.jpg"
  },
  {
    "id": 48,
    "kamiNoKu": "風をいたみ 岩うつ波の おのれのみ",
    "shimoNoKu": "くだけて物を 思ふころかな",
    "kamiNoKuKana": "かぜをいたみ いはうつなみの おのれのみ",
    "shimoNoKuKana": "くだけてものを おもふころかな",
    "kimariji": "かぜを",
    "author": "源重之",
    "authorKana": "みなもとのしげゆき",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/9/97/Hyakuninisshu_048.jpg"
  },
  {
    "id": 49,
    "kamiNoKu": "みかきもり 衛士のたく火の 夜はもえ",
    "shimoNoKu": "昼は消えつつ 物をこそ思へ",
    "kamiNoKuKana": "みかきもり ゑじのたくひの よるはもえ",
    "shimoNoKuKana": "ひるはきえつつ ものをこそおもへ",
    "kimariji": "みかき",
    "author": "大中臣能宣朝臣",
    "authorKana": "おおなかとみのよしのぶあそん",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/b/b8/Hyakuninisshu_049.jpg"
  },
  {
    "id": 50,
    "kamiNoKu": "君がため 惜しからざりし いのちさへ",
    "shimoNoKu": "長くもがなと 思ひけるかな",
    "kamiNoKuKana": "きみがため をしからざりし いのちさへ",
    "shimoNoKuKana": "ながくもがなと おもひけるかな",
    "kimariji": "きみがため を",
    "author": "藤原義孝",
    "authorKana": "ふじわらのよしたか",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/8/85/Hyakuninisshu_050.jpg"
  },
  {
    "id": 51,
    "kamiNoKu": "かくとだに えやはいぶきの さしも草",
    "shimoNoKu": "さしもしらじな もゆる思ひを",
    "kamiNoKuKana": "かくとだに えやはいぶきの さしもぐさ",
    "shimoNoKuKana": "さしもしらじな もゆるおもひを",
    "kimariji": "かく",
    "author": "藤原実方朝臣",
    "authorKana": "ふじわらのさねかたあそん",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/4/48/Hyakuninisshu_051.jpg"
  },
  {
    "id": 52,
    "kamiNoKu": "あけぬれば 暮るるものとは 知りながら",
    "shimoNoKu": "なほうらめしき 朝ぼらけかな",
    "kamiNoKuKana": "あけぬれば くるるものとは しりながら",
    "shimoNoKuKana": "なほうらめしき あさぼらけかな",
    "kimariji": "あけ",
    "author": "藤原道信朝臣",
    "authorKana": "ふじわらのみちのぶあそん",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/0/08/Hyakuninisshu_052.jpg"
  },
  {
    "id": 53,
    "kamiNoKu": "なげきつつ ひとりぬる夜の あくるまは",
    "shimoNoKu": "いかに久しき ものとかはしる",
    "kamiNoKuKana": "なげきつつ ひとりぬるよの あくるまは",
    "shimoNoKuKana": "いかにひさしき ものとかはしる",
    "kimariji": "なげき",
    "author": "右大将道綱母",
    "authorKana": "うだいしょうみちつなのはは",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/0/02/Hyakuninisshu_053.jpg"
  },
  {
    "id": 54,
    "kamiNoKu": "忘れじの ゆく末までは かたければ",
    "shimoNoKu": "今日をかぎりの いのちともがな",
    "kamiNoKuKana": "わすれじの ゆくすゑまでは かたければ",
    "shimoNoKuKana": "けふをかぎりの いのちともがな",
    "kimariji": "わすれ",
    "author": "儀同三司母",
    "authorKana": "ぎどうさんしのはは",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/a/a0/Hyakuninisshu_054.jpg"
  },
  {
    "id": 55,
    "kamiNoKu": "滝の音は たえて久しく なりぬれど",
    "shimoNoKu": "名こそ流れて なほ聞こえけれ",
    "kamiNoKuKana": "たきのおとは たえてひさしく なりぬれど",
    "shimoNoKuKana": "なこそながれて なほきこえけれ",
    "kimariji": "たき",
    "author": "大納言公任",
    "authorKana": "だいなごんきんとう",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/3/31/Hyakuninisshu_055.jpg"
  },
  {
    "id": 56,
    "kamiNoKu": "あらざらむ この世のほかの 思ひ出に",
    "shimoNoKu": "いまひとたびの あふこともがな",
    "kamiNoKuKana": "あらざらむ このよのほかの おもひでに",
    "shimoNoKuKana": "いまひとたびの あふこともがな",
    "kimariji": "あらざ",
    "author": "和泉式部",
    "authorKana": "いずみしきぶ",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/9/99/Hyakuninisshu_056.jpg"
  },
  {
    "id": 57,
    "kamiNoKu": "めぐりあひて 見しやそれとも わかぬまに",
    "shimoNoKu": "雲がくれにし 夜半の月かな",
    "kamiNoKuKana": "めぐりあひて みしやそれとも わかぬまに",
    "shimoNoKuKana": "くもがくれにし よはのつきかな",
    "kimariji": "め",
    "author": "紫式部",
    "authorKana": "むらさきしきぶ",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/1/13/Hyakuninisshu_057.jpg"
  },
  {
    "id": 58,
    "kamiNoKu": "ありま山 ゐなの笹原 風吹けば",
    "shimoNoKu": "いでそよ人を 忘れやはする",
    "kamiNoKuKana": "ありまやま ゐなのささはら かぜふけば",
    "shimoNoKuKana": "いでそよひとを わすれやはする",
    "kimariji": "ありま",
    "author": "大弐三位",
    "authorKana": "だいにのさんみ",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/7/71/Hyakuninisshu_058.jpg"
  },
  {
    "id": 59,
    "kamiNoKu": "やすらはで 寝なましものを さ夜ふけて",
    "shimoNoKu": "かたぶくまでの 月を見しかな",
    "kamiNoKuKana": "やすらはで ねなましものを さよふけて",
    "shimoNoKuKana": "かたぶくまでの つきをみしかな",
    "kimariji": "やす",
    "author": "赤染衛門",
    "authorKana": "あかぞめえもん",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/0/0f/Hyakuninisshu_059.jpg"
  },
  {
    "id": 60,
    "kamiNoKu": "大江山 いく野の道の 遠ければ",
    "shimoNoKu": "まだふみもみず 天の橋立",
    "kamiNoKuKana": "おほえやま いくののみちの とほければ",
    "shimoNoKuKana": "まだふみもみず あまのはしだて",
    "kimariji": "おほえ",
    "author": "小式部内侍",
    "authorKana": "こしきぶのないし",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/a/ae/Hyakuninisshu_060.jpg"
  },
  {
    "id": 61,
    "kamiNoKu": "いにしへの 奈良の都の 八重桜",
    "shimoNoKu": "けふ九重に 匂ひぬるかな",
    "kamiNoKuKana": "いにしへの ならのみやこの やへざくら",
    "shimoNoKuKana": "けふここのへに にほひぬるかな",
    "kimariji": "いに",
    "author": "伊勢大輔",
    "authorKana": "いせのたいふ",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/f/fb/Hyakuninisshu_061.jpg"
  },
  {
    "id": 62,
    "kamiNoKu": "夜をこめて 鳥のそらねは はかるとも",
    "shimoNoKu": "よに逢坂の 関はゆるさじ",
    "kamiNoKuKana": "よをこめて とりのそらねは はかるとも",
    "shimoNoKuKana": "よにあふさかの せきはゆるさじ",
    "kimariji": "よを",
    "author": "清少納言",
    "authorKana": "せいしょうなごん",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/d/d7/Hyakuninisshu_062.jpg"
  },
  {
    "id": 63,
    "kamiNoKu": "いまはただ 思ひ絶えなむ とばかりを",
    "shimoNoKu": "人づてならで 言ふよしもがな",
    "kamiNoKuKana": "いまはただ おもひたえなむ とばかりを",
    "shimoNoKuKana": "ひとづてならで いふよしもがな",
    "kimariji": "いまは",
    "author": "左京大夫道雅",
    "authorKana": "さきょうのだいぶみちまさ",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/b/be/Hyakuninisshu_063.jpg"
  },
  {
    "id": 64,
    "kamiNoKu": "朝ぼらけ 宇治の川霧 絶え絶えに",
    "shimoNoKu": "あらはれわたる 瀬々の網代木",
    "kamiNoKuKana": "あさぼらけ うぢのかはぎり たえだえに",
    "shimoNoKuKana": "あらはれわたる せぜのあじろぎ",
    "kimariji": "あさぼらけ う",
    "author": "権中納言定頼",
    "authorKana": "ごんちゅうなごんさだより",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/2/25/Hyakuninisshu_064.jpg"
  },
  {
    "id": 65,
    "kamiNoKu": "うらみわび ほさぬ袖だに あるものを",
    "shimoNoKu": "恋にくちなむ 名こそをしけれ",
    "kamiNoKuKana": "うらみわび ほさぬそでだに あるものを",
    "shimoNoKuKana": "こひにくちなむ なこそをしけれ",
    "kimariji": "うら",
    "author": "相模",
    "authorKana": "さがみ",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/5/51/Hyakuninisshu_065.jpg"
  },
  {
    "id": 66,
    "kamiNoKu": "もろともに あはれと思へ 山桜",
    "shimoNoKu": "花よりほかに 知る人もなし",
    "kamiNoKuKana": "もろともに あはれとおもへ やまざくら",
    "shimoNoKuKana": "はなよりほかに しるひともなし",
    "kimariji": "もろ",
    "author": "前大僧正行尊",
    "authorKana": "さきのだいそうじょうぎょうそん",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/2/26/Hyakuninisshu_066.jpg"
  },
  {
    "id": 67,
    "kamiNoKu": "春の夜の 夢ばかりなる 手枕に",
    "shimoNoKu": "かひなくたたむ 名こそをしけれ",
    "kamiNoKuKana": "はるのよの ゆめばかりなる たまくらに",
    "shimoNoKuKana": "かひなくたたむ なこそをしけれ",
    "kimariji": "はるの",
    "author": "周防内侍",
    "authorKana": "すおうのないし",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/9/93/Hyakuninisshu_067.jpg"
  },
  {
    "id": 68,
    "kamiNoKu": "心にも あらでうき世に ながらへば",
    "shimoNoKu": "恋しかるべき 夜半の月かな",
    "kamiNoKuKana": "こころにも あらでうきよに ながらへば",
    "shimoNoKuKana": "こひしかるべき よはのつきかな",
    "kimariji": "こころに",
    "author": "三条院",
    "authorKana": "さんじょういん",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/0/0e/Hyakuninisshu_068.jpg"
  },
  {
    "id": 69,
    "kamiNoKu": "あらし吹く み室の山の もみぢばは",
    "shimoNoKu": "竜田の川の 錦なりけり",
    "kamiNoKuKana": "あらしふく みむろのやまの もみぢばは",
    "shimoNoKuKana": "たつたのかはの にしきなりけり",
    "kimariji": "あらし",
    "author": "能因法師",
    "authorKana": "のういんほうし",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/d/d9/Hyakuninisshu_069.jpg"
  },
  {
    "id": 70,
    "kamiNoKu": "さびしさに 宿を立ち出でて ながむれば",
    "shimoNoKu": "いづくもおなじ 秋の夕ぐれ",
    "kamiNoKuKana": "さびしさに やどをたちいでて ながむれば",
    "shimoNoKuKana": "いづくもおなじ あきのゆふぐれ",
    "kimariji": "さ",
    "author": "良選法師",
    "authorKana": "りょうぜんほうし",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/7/75/Hyakuninisshu_070.jpg"
  },
  {
    "id": 71,
    "kamiNoKu": "夕されば 門田の稲葉 おとづれて",
    "shimoNoKu": "蘆のまろやに 秋風ぞ吹く",
    "kamiNoKuKana": "ゆふされば かどたのいなば おとづれて",
    "shimoNoKuKana": "あしのまろやに あきかぜぞふく",
    "kimariji": "ゆふ",
    "author": "大納言経信",
    "authorKana": "だいなごんつねのぶ",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/1/1b/Hyakuninisshu_071.jpg"
  },
  {
    "id": 72,
    "kamiNoKu": "音に聞く 高師の浜の あだ波は",
    "shimoNoKu": "かけじや袖の ぬれもこそすれ",
    "kamiNoKuKana": "おとにきく たかしのはまの あだなみは",
    "shimoNoKuKana": "かけじやそでの ぬれもこそすれ",
    "kimariji": "おと",
    "author": "祐子内親王家紀伊",
    "authorKana": "ゆうしないしんのうけのきい",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/2/2b/Hyakuninisshu_072.jpg"
  },
  {
    "id": 73,
    "kamiNoKu": "高砂の をのへのさくら さきにけり",
    "shimoNoKu": "とやまのかすみ たたずもあらなむ",
    "kamiNoKuKana": "たかさごの をのへのさくら さきにけり",
    "shimoNoKuKana": "とやまのかすみ たたずもあらなむ",
    "kimariji": "たか",
    "author": "前権中納言匡房",
    "authorKana": "さきのごんちゅうなごんまさふさ",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/a/a2/Hyakuninisshu_073.jpg"
  },
  {
    "id": 74,
    "kamiNoKu": "憂かりける 人を初瀬の 山おろしよ",
    "shimoNoKu": "はげしかれとは 祈らぬものを",
    "kamiNoKuKana": "うかりける ひとをはつせの やまおろしよ",
    "shimoNoKuKana": "はげしかれとは いのらぬものを",
    "kimariji": "うか",
    "author": "源俊頼朝臣",
    "authorKana": "みなもとのとしよりあそん",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/0/00/Hyakuninisshu_074.jpg"
  },
  {
    "id": 75,
    "kamiNoKu": "ちぎりおきし させもが露を いのちにて",
    "shimoNoKu": "あはれ今年の 秋もいぬめり",
    "kamiNoKuKana": "ちぎりおきし させもがつゆを いのちにて",
    "shimoNoKuKana": "あはれことしの あきもいぬめり",
    "kimariji": "ちぎりお",
    "author": "藤原基俊",
    "authorKana": "ふじわらのもととし",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/5/55/Hyakuninisshu_075.jpg"
  },
  {
    "id": 76,
    "kamiNoKu": "わたの原 こぎいでてみれば 久方の",
    "shimoNoKu": "雲いにまがふ 沖つ白波",
    "kamiNoKuKana": "わたのはら こぎいでてみれば ひさかたの",
    "shimoNoKuKana": "くもゐにまがふ おきつしらなみ",
    "kimariji": "わたのはら こ",
    "author": "法性寺入道前関白太政大臣",
    "authorKana": "ほつしょうじにゅうどうさきの かんぱくだいじょうだいじん",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/d/da/Hyakuninisshu_076.jpg"
  },
  {
    "id": 77,
    "kamiNoKu": "瀬をはやみ 岩にせかるる 滝川の",
    "shimoNoKu": "われても末に あはむとぞ思ふ",
    "kamiNoKuKana": "せをはやみ いはにせかるる たきがはの",
    "shimoNoKuKana": "われてもすゑに あはむとぞおもふ",
    "kimariji": "せ",
    "author": "崇徳院",
    "authorKana": "すとくいん",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/e/e2/Hyakuninisshu_077.jpg"
  },
  {
    "id": 78,
    "kamiNoKu": "淡路島 かよふ千鳥の 鳴く声に",
    "shimoNoKu": "幾夜ねざめぬ 須磨の関守",
    "kamiNoKuKana": "あはぢしま かよふちどりの なくこゑに",
    "shimoNoKuKana": "いくよねざめぬ すまのせきもり",
    "kimariji": "あはぢ",
    "author": "源兼昌",
    "authorKana": "みなもとのかねまさ",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/b/bf/Hyakuninisshu_078.jpg"
  },
  {
    "id": 79,
    "kamiNoKu": "秋風に たなびく雲の たえ間より",
    "shimoNoKu": "もれいづる月の 影のさやけさ",
    "kamiNoKuKana": "あきかぜに たなびくくもの たえまより",
    "shimoNoKuKana": "もれいづるつきの かげのさやけさ",
    "kimariji": "あきか",
    "author": "左京大夫顕輔",
    "authorKana": "さきょうのだいぶあきすけ",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/1/1d/Hyakuninisshu_079.jpg"
  },
  {
    "id": 80,
    "kamiNoKu": "長からむ 心もしらず 黒髪の",
    "shimoNoKu": "みだれてけさは 物をこそ思へ",
    "kamiNoKuKana": "ながからむ こころもしらず くろかみの",
    "shimoNoKuKana": "みだれてけさは ものをこそおもへ",
    "kimariji": "ながか",
    "author": "待賢門院堀河",
    "authorKana": "たいけんもんいんほりかわ",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/f/f9/Hyakuninisshu_080.jpg"
  },
  {
    "id": 81,
    "kamiNoKu": "ほととぎす 鳴きつる方を ながむれば",
    "shimoNoKu": "ただありあけの 月ぞ残れる",
    "kamiNoKuKana": "ほととぎす なきつるかたを ながむれば",
    "shimoNoKuKana": "ただありあけの つきぞのこれる",
    "kimariji": "ほ",
    "author": "後徳大寺左大臣",
    "authorKana": "ごとくだいじさだいじん",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/d/da/Hyakuninisshu_081.jpg"
  },
  {
    "id": 82,
    "kamiNoKu": "思ひわび さてもいのちは あるものを",
    "shimoNoKu": "憂きにたへぬは 涙なりけり",
    "kamiNoKuKana": "おもひわび さてもいのちは あるものを",
    "shimoNoKuKana": "うきにたへぬは なみだなりけり",
    "kimariji": "おも",
    "author": "道因法師",
    "authorKana": "どういんほうし",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/f/f2/Hyakuninisshu_082.jpg"
  },
  {
    "id": 83,
    "kamiNoKu": "世の中よ 道こそなけれ 思ひ入る",
    "shimoNoKu": "山の奥にも 鹿ぞ鳴くなる",
    "kamiNoKuKana": "よのなかよ みちこそなけれ おもひいる",
    "shimoNoKuKana": "やまのおくにも しかぞなくなる",
    "kimariji": "よのなかよ",
    "author": "皇太后宮大夫俊成",
    "authorKana": "こうたいごうぐうのだいぶしゅんぜい",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/b/be/Hyakuninisshu_083.jpg"
  },
  {
    "id": 84,
    "kamiNoKu": "ながらへば またこのごろや しのばれむ",
    "shimoNoKu": "憂しと見し世ぞ 今は恋しき",
    "kamiNoKuKana": "ながらへば またこのごろや しのばれむ",
    "shimoNoKuKana": "うしとみしよぞ いまはこひしき",
    "kimariji": "ながら",
    "author": "藤原清輔朝臣",
    "authorKana": "ふじわらのきよすけあそん",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/0/05/Hyakuninisshu_084.jpg"
  },
  {
    "id": 85,
    "kamiNoKu": "夜もすがら 物思ふころは 明けやらで",
    "shimoNoKu": "閨のひまさへ つれなかりけり",
    "kamiNoKuKana": "よもすがら ものおもふころは あけやらで",
    "shimoNoKuKana": "ねやのひまさへ つれなかりけり",
    "kimariji": "よも",
    "author": "俊恵法師",
    "authorKana": "しゅんえほうし",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/0/06/Hyakuninisshu_085.jpg"
  },
  {
    "id": 86,
    "kamiNoKu": "なげけとて 月やは物を 思はする",
    "shimoNoKu": "かこち顔なる わが涙かな",
    "kamiNoKuKana": "なげけとて つきやはものを おもはする",
    "shimoNoKuKana": "かこちがほなる わがなみだかな",
    "kimariji": "なげけ",
    "author": "西行法師",
    "authorKana": "さいぎょうほうし",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/6/61/Hyakuninisshu_086.jpg"
  },
  {
    "id": 87,
    "kamiNoKu": "村雨の 露もまだひぬ まきの葉に",
    "shimoNoKu": "霧たちのぼる 秋の夕ぐれ",
    "kamiNoKuKana": "むらさめの つゆもまだひぬ まきのはに",
    "shimoNoKuKana": "きりたちのぼる あきのゆふぐれ",
    "kimariji": "む",
    "author": "寂蓮法師",
    "authorKana": "じゃくれんほうし",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/9/9f/Hyakuninisshu_087.jpg"
  },
  {
    "id": 88,
    "kamiNoKu": "難波江の 蘆のかりねの ひとよゆゑ",
    "shimoNoKu": "みをつくしてや 恋ひわたるべき",
    "kamiNoKuKana": "なにはえの あしのかりねの ひとよゆゑ",
    "shimoNoKuKana": "みをつくしてや こひわたるべき",
    "kimariji": "なにはえ",
    "author": "皇嘉門院別当",
    "authorKana": "こうかもんいんのべつとう",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/4/4c/Hyakuninisshu_088.jpg"
  },
  {
    "id": 89,
    "kamiNoKu": "玉の緒よ たえなばたえね ながらへば",
    "shimoNoKu": "忍ぶることの 弱りもぞする",
    "kamiNoKuKana": "たまのをよ たえなばたえね ながらへば",
    "shimoNoKuKana": "しのぶることの よわりもぞする",
    "kimariji": "たま",
    "author": "式子内親王",
    "authorKana": "しきしないしんのう",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/b/b1/Hyakuninisshu_089.jpg"
  },
  {
    "id": 90,
    "kamiNoKu": "見せばやな 雄島のあまの 袖だにも",
    "shimoNoKu": "ぬれにぞぬれし 色はかはらず",
    "kamiNoKuKana": "みせばやな をじまのあまの そでだにも",
    "shimoNoKuKana": "ぬれにぞぬれし いろはかはらず",
    "kimariji": "みせ",
    "author": "殷富門院大輔",
    "authorKana": "いんぶもんいんのたいふ",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/8/82/Hyakuninisshu_090.jpg"
  },
  {
    "id": 91,
    "kamiNoKu": "きりぎりす 鳴くや霜夜の さむしろに",
    "shimoNoKu": "衣かたしき ひとりかも寝む",
    "kamiNoKuKana": "きりぎりす なくやしもよの さむしろに",
    "shimoNoKuKana": "ころもかたしき ひとりかもねむ",
    "kimariji": "きり",
    "author": "後京極摂政前太政大臣",
    "authorKana": "ごきょうごくせっしょうさきのだいじょうだいじん",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/c/c3/Hyakuninisshu_091.jpg"
  },
  {
    "id": 92,
    "kamiNoKu": "わが袖は 潮干にみえぬ 沖の石の",
    "shimoNoKu": "人こそしらね かわくまもなし",
    "kamiNoKuKana": "わがそでは しほひにみえぬ おきのいしの",
    "shimoNoKuKana": "ひとこそしらね かわくまもなし",
    "kimariji": "わがそ",
    "author": "二条院讃岐",
    "authorKana": "にじょういんのさぬき",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/d/d2/Hyakuninisshu_092.jpg"
  },
  {
    "id": 93,
    "kamiNoKu": "世の中は つねにもがもな なぎさこぐ",
    "shimoNoKu": "あまの小舟の 綱手かなしも",
    "kamiNoKuKana": "よのなかは つねにもがもな なぎさこぐ",
    "shimoNoKuKana": "あまのをぶねの つなでかなしも",
    "kimariji": "よのなかは",
    "author": "鎌倉右大臣",
    "authorKana": "かまくらのうだいじん",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/f/f2/Hyakuninisshu_093.jpg"
  },
  {
    "id": 94,
    "kamiNoKu": "み吉野の 山の秋風 さ夜ふけて",
    "shimoNoKu": "ふるさと寒く 衣うつなり",
    "kamiNoKuKana": "みよしのの やまのあきかぜ さよふけて",
    "shimoNoKuKana": "ふるさとさむく ころもうつなり",
    "kimariji": "みよ",
    "author": "参議雅経",
    "authorKana": "さんぎまさつね",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/2/2f/Hyakuninisshu_094.jpg"
  },
  {
    "id": 95,
    "kamiNoKu": "おほけなく うき世の民に おほふかな",
    "shimoNoKu": "わがたつ杣に 墨染の袖",
    "kamiNoKuKana": "おほけなく うきよのたみに おほふかな",
    "shimoNoKuKana": "わがたつそまに すみぞめのそで",
    "kimariji": "おほけ",
    "author": "前大僧正慈円",
    "authorKana": "さきのだいそうじょうじえん",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/a/a6/Hyakuninisshu_095.jpg"
  },
  {
    "id": 96,
    "kamiNoKu": "花さそふ 嵐の庭の 雪ならで",
    "shimoNoKu": "ふりゆくものは わが身なりけり",
    "kamiNoKuKana": "はなさそふ あらしのにはの ゆきならで",
    "shimoNoKuKana": "ふりゆくものは わがみなりけり",
    "kimariji": "はなさ",
    "author": "入道前太政大臣",
    "authorKana": "にゅうどうさきのだいじょうだいじん",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/8/83/Hyakuninisshu_096.jpg"
  },
  {
    "id": 97,
    "kamiNoKu": "こぬ人を まつほの浦の 夕なぎに",
    "shimoNoKu": "焼くやもしほの 身もこがれつつ",
    "kamiNoKuKana": "こぬひとを まつほのうらの ゆふなぎに",
    "shimoNoKuKana": "やくやもしほの みもこがれつつ",
    "kimariji": "こぬ",
    "author": "権中納言定家",
    "authorKana": "ごんちゅうなごんていか",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/c/cb/Hyakuninisshu_097.jpg"
  },
  {
    "id": 98,
    "kamiNoKu": "風そよぐ ならの小川の 夕ぐれは",
    "shimoNoKu": "みそぎぞ夏の しるしなりける",
    "kamiNoKuKana": "かぜそよぐ ならのをがはの ゆふぐれは",
    "shimoNoKuKana": "みそぎぞなつの しるしなりける",
    "kimariji": "かぜそ",
    "author": "従二位家隆",
    "authorKana": "じゅうにいいえたか",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/0/00/Hyakuninisshu_098.jpg"
  },
  {
    "id": 99,
    "kamiNoKu": "人もをし 人もうらめし あぢきなく",
    "shimoNoKu": "世を思ふゆゑに 物思ふ身は",
    "kamiNoKuKana": "ひともをし ひともうらめし あぢきなく",
    "shimoNoKuKana": "よをおもふゆゑに ものおもふみは",
    "kimariji": "ひとも",
    "author": "後鳥羽院",
    "authorKana": "ごとばいん",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/8/8c/Hyakuninisshu_099.jpg"
  },
  {
    "id": 100,
    "kamiNoKu": "ももしきや ふるき軒ばの しのぶにも",
    "shimoNoKu": "なほあまりある 昔なりけり",
    "kamiNoKuKana": "ももしきや ふるきのきばの しのぶにも",
    "shimoNoKuKana": "なほあまりある むかしなりけり",
    "kimariji": "もも",
    "author": "順徳院",
    "authorKana": "じゅんとくいん",
    "imageURL": "http://upload.wikimedia.org/wikipedia/commons/f/ff/Hyakuninisshu_100.jpg"
  }
] as const;
